# Generated by Django 5.2.5 on 2025-11-15 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_app', '0002_alter_discount_product'),
        ('product_app', '0007_alter_comments_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_app.product'),
        ),
    ]
