# Generated by Django 5.2.5 on 2025-11-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0005_alter_comments_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together=set(),
        ),
    ]
