# Generated by Django 5.2.5 on 2025-11-15 11:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0006_alter_comments_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comments',
            unique_together={('product', 'user')},
        ),
    ]
